
enum class ControlType {
    MOUSE_MOVE = 0,

    MOUSE_DOWN = 1,

    MOUSE_UP = 2,

    INPUT_TEXT = 3,

    BACK = 5,

    HOME = 6,

    RECENT = 7,

    UNLOCK_SCREEN = 8,

    REBOOT = 10,

    RERENDER_FRAME = 20,


    CONNECT_PROXY = 21,

    DISCONNECT_PROXY = 22,

    RESET_FACTORY = 23,

    SCREEN_SHOT = 30,

    GET_XML = 31,
    GET_CLIPBOARD = 32,


    GET_DEVICE_INFO = 33,
    GET_INSTALLED_PACKAGE = 40,
    OPEN_PACKAGE = 41,
    OPEN_APP_INFO = 42,
    FORCE_STOP = 43,
    CLEAR_APP = 44,
    UNINSTALL_APP = 45,
    BACKUP_APP = 46,
    RESTORE_DEVICE = 47,
    CHANGE_DEVICE = 48,
    EXECUTE_SINGLE_NODE = 50,

    BUSINESS_TAP = 1001,
    BUSINESS_SWIPE = 1002,
    BUSINESS_INPUT_TEXT = 1003,
    BUSINESS_DUMP_XML = 1004,
    BUSINESS_SHELL = 1005,
    BUSSINESS_TAP_XPATH = 1006,
    BUSSINESS_INPUT_XPATH = 1007,

    SWITCH_GO_TIENG_VIET = 10000,
};

enum class ReportControlType{
    EXPORT_START = 0,
    EXPORT_CONTENT = 1,
    EXPORT_COMPLETE = 2,

    EXPORT_LOG = 3,
    EXPORT_CLIPBOARD = 4,
    EXPORT_XML = 5,
    EXPORT_SCREEN_SHOT = 6,
    EXPORT_INSTALLED_PACKAGE = 7,
    EXPORT_DEVICE_INFO = 8,
    EXPORT_FILE = 9,

    EXPORT_SHELL_RESULT = 10,
    EXPORT_TAP_XPATH_RESULT = 11,
    EXPORT_INPUT_XPATH_RESULT = 12,

    EXPORT_SCREEN_ROTATION = 20,
};


enum class FileTranferType{
    FILE_METADATA = 0,
    FILE_COMPLETE = 1,
    INSTALL_APK = 2,
    RESTORE_APP = 3,
};